---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.10.4
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-kube-audit-rest
  namespace: elastic-system
spec:
  version: 8.10.4
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config: 
    telemetry:
      optIn: false
